In [3]:
import pandas as pd
import numpy as np
import math

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Pandas 数据导入与导出

### 分隔符分隔的文本文件导入

#导入csv格式文件
data = pd.read_csv(filename,header=None,names=[],skiprows=1)
#默认会将文件第一行作为column names,如果源文件中没有header,设置header=None
#通过names参数可以指定column names
#skiprows指定需要跳过前几行，也有其他的参数用于跳过后面几行
#---
#导入分隔符文本中的数据
data = pd.read_table()


### 基于URL链接从网页解析导入表格数据

In [10]:
import requests
import lxml
import html5lib

In [52]:
f_states =   pd.read_html('https://simple.wikipedia.org/wiki/List_of_U.S._states')

In [53]:
#取出第一个表格
f_states[0].head(5)

0             1           2            3                  4
0  Sl no.  Abbreviation  State Name      Capital     Became a State
1       1            AL     Alabama   Montgomery  December 14, 1819
2       2            AK      Alaska       Juneau    January 3, 1959
3       3            AZ     Arizona      Phoenix  February 14, 1912
4       4            AR    Arkansas  Little Rock      June 15, 1836

In [57]:
my_columns = f_states[0].loc[0]
copy_df = f_states[0][1:]
copy_df.columns = my_columns
copy_df.head(5)

0 Sl no. Abbreviation  State Name      Capital     Became a State
1      1           AL     Alabama   Montgomery  December 14, 1819
2      2           AK      Alaska       Juneau    January 3, 1959
3      3           AZ     Arizona      Phoenix  February 14, 1912
4      4           AR    Arkansas  Little Rock      June 15, 1836
5      5           CA  California   Sacramento  September 9, 1850

### 导入系统剪贴板中的数据

In [25]:
cp_df = pd.read_clipboard(header=None,names=['GEO_id'])
cp_df

GEO_id
0  GSE33265
1  GSE98924
2  GSE81069
3  GSE86272

### 数据导出

- 导出为csv格式的文件

    df.to_csv(filename)

当然其他格式，比如excel,json等都可以导出


## Pandas DataFrame数据索引

- 使用基本[]索引数据
- 使用.列名索引数据
- 使用.loc()方法索引数据
- 使用.iloc()方法索引数据
- .isin()过滤筛选
- .query()
- .str.contains()使用正则表达式匹配过滤

### 用于测试的数据

In [32]:
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})
df.index = ['LOC_a','LOC_b','c']
df

A  B  C
LOC_a  1  4  7
LOC_b  2  5  8
c      3  6  9

### 使用基本[]索引数据

In [33]:
df['A']

LOC_a    1
LOC_b    2
c        3
Name: A, dtype: int64

In [35]:
df[1:]

A  B  C
LOC_b  2  5  8
c      3  6  9

### 使用.列名索引数据

In [34]:
df.A

LOC_a    1
LOC_b    2
c        3
Name: A, dtype: int64

### 使用.loc()方法索引数据

In [ ]:
#.loc() 按名称索引
df.loc[:,'A']

In [ ]:
df.loc[:,['A','C']]

In [41]:
df.loc['c']

A    3
B    6
C    9
Name: c, dtype: int64

In [ ]:
df.loc[['LOC_a','c'],:]

### 使用.iloc()方法索引数据

In [ ]:
#.iloc()按位置序列索引
df.iloc[:,1]

In [ ]:
df.iloc[[0,2],2]

### .str.contains()使用正则表达式匹配过滤

In [ ]:
df[df.index.str.contains(r'LOC')]

### 使用query()条件过滤

In [ ]:
df.query("A>=2 & (B>=4 | C>=7)")

## DataFrame 基本信息

- 查看index，数据类型
    df.info()
- 查看描述性的统计信息
    df.describe()
- 查看数据出现频数
    df.A.value_counts()
  

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, LOC_a to c
Data columns (total 3 columns):
A    3 non-null int64
B    3 non-null int64
C    3 non-null int64
dtypes: int64(3)
memory usage: 176.0+ bytes


In [59]:
df.describe()

A    B    C
count  3.0  3.0  3.0
mean   2.0  5.0  8.0
std    1.0  1.0  1.0
min    1.0  4.0  7.0
25%    1.5  4.5  7.5
50%    2.0  5.0  8.0
75%    2.5  5.5  8.5
max    3.0  6.0  9.0

In [64]:
df.A.value_counts()

3    1
2    1
1    1
Name: A, dtype: int64

## DataFrame数据计算问题

In [ ]:
df.apply(lambda s:s*2+1)

In [65]:
df.apply(pd.Series.value_counts)

A    B    C
1  1.0  NaN  NaN
2  1.0  NaN  NaN
3  1.0  NaN  NaN
4  NaN  1.0  NaN
5  NaN  1.0  NaN
6  NaN  1.0  NaN
7  NaN  NaN  1.0
8  NaN  NaN  1.0
9  NaN  NaN  1.0

In [ ]:
### 对某一列的操作可以使用map函数
df.A.map(lambda s:s*2+1)

通过某列值的大小新增一列,下面是一个实战中的例子:

`merge_fpkm_DEG['DEG_statue'] = merge_fpkm_DEG.apply(lambda x: 'Down' if x.log2FoldChange>=0 else 'Up', axis=1)`

## === END TEST ===

In [18]:
import json

In [21]:
with open('JSON_findPerfectMatches_and_TerminalMisMatches_v3') as f:
    data = json.load(f)

In [24]:
import re

In [29]:
test_string = 'MD:Z:0A24'

In [30]:
if re.match(r'MD:Z:0[A,T,C,G]\d+?',test_string):
    print('M')
else:
    print('NM')

M


In [36]:
(89-np.mean([89,72,94,69]))/np.std([89,72,94,69],ddof=1)

0.647467353462031

In [37]:
(96-np.mean([96,74,87,78]))/np.std([96,74,87,78],ddof=1)

1.2486356190221826

In [38]:
def normalEqn(X, y):
    theta = np.linalg.inv(X.T@X)@X.T@y #X.T@X等价于X.T.dot(X)
    return theta

In [40]:
sample = np.array([1,2104,5,1,45,1,1416,3,2,40,1,1534,3,2,30,1,852,2,1,36]).reshape([4,5])

In [41]:
sample

array([[   1, 2104,    5,    1,   45],
       [   1, 1416,    3,    2,   40],
       [   1, 1534,    3,    2,   30],
       [   1,  852,    2,    1,   36]])

In [42]:
y = np.array([460,232,315,178]).reshape([4,1])
y

array([[460],
       [232],
       [315],
       [178]])

In [43]:
normalEqn(sample,y)

array([[ 4.36875000e+02],
       [ 2.87841797e-01],
       [-9.62500000e+01],
       [-9.00625000e+01],
       [-4.50390625e+00]])

In [51]:
a='abcLOC_\nabcOs01gabc'
print(a.rstrip('abc'))

abcLOC_
abcOs01g


In [52]:
print('hello')

hello
