<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Pandas-数据导入与导出" data-toc-modified-id="Pandas-数据导入与导出-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Pandas 数据导入与导出</a></span><ul class="toc-item"><li><span><a href="#分隔符分隔的文本文件导入" data-toc-modified-id="分隔符分隔的文本文件导入-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>分隔符分隔的文本文件导入</a></span></li><li><span><a href="#基于URL链接从网页解析导入表格数据" data-toc-modified-id="基于URL链接从网页解析导入表格数据-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>基于URL链接从网页解析导入表格数据</a></span></li><li><span><a href="#导入系统剪贴板中的数据" data-toc-modified-id="导入系统剪贴板中的数据-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>导入系统剪贴板中的数据</a></span></li><li><span><a href="#数据导出" data-toc-modified-id="数据导出-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>数据导出</a></span></li></ul></li><li><span><a href="#Pandas-DataFrame数据选择（切片与其他数据获得方式）" data-toc-modified-id="Pandas-DataFrame数据选择（切片与其他数据获得方式）-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Pandas DataFrame数据选择（切片与其他数据获得方式）</a></span><ul class="toc-item"><li><span><a href="#用于测试的数据" data-toc-modified-id="用于测试的数据-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>用于测试的数据</a></span></li><li><span><a href="#使用[]索引数据" data-toc-modified-id="使用[]索引数据-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>使用[]索引数据</a></span><ul class="toc-item"><li><span><a href="#列索引" data-toc-modified-id="列索引-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>列索引</a></span></li><li><span><a href="#行索引" data-toc-modified-id="行索引-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>行索引</a></span></li></ul></li><li><span><a href="#使用.列名索引列数据" data-toc-modified-id="使用.列名索引列数据-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>使用.列名索引列数据</a></span></li><li><span><a href="#使用.loc()方法索引数据" data-toc-modified-id="使用.loc()方法索引数据-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>使用.loc()方法索引数据</a></span></li><li><span><a href="#使用.iloc()方法索引数据" data-toc-modified-id="使用.iloc()方法索引数据-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>使用.iloc()方法索引数据</a></span></li><li><span><a href="#条件过滤索引" data-toc-modified-id="条件过滤索引-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>条件过滤索引</a></span><ul class="toc-item"><li><span><a href="#.loc[]条件过滤" data-toc-modified-id=".loc[]条件过滤-2.6.1"><span class="toc-item-num">2.6.1&nbsp;&nbsp;</span>.loc[]条件过滤</a></span></li><li><span><a href="#.str.contains()使用正则表达式匹配过滤" data-toc-modified-id=".str.contains()使用正则表达式匹配过滤-2.6.2"><span class="toc-item-num">2.6.2&nbsp;&nbsp;</span>.str.contains()使用正则表达式匹配过滤</a></span></li><li><span><a href="#使用query()条件过滤" data-toc-modified-id="使用query()条件过滤-2.6.3"><span class="toc-item-num">2.6.3&nbsp;&nbsp;</span>使用query()条件过滤</a></span></li></ul></li><li><span><a href="#层级索引" data-toc-modified-id="层级索引-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>层级索引</a></span><ul class="toc-item"><li><span><a href="#多级索引Series" data-toc-modified-id="多级索引Series-2.7.1"><span class="toc-item-num">2.7.1&nbsp;&nbsp;</span>多级索引Series</a></span><ul class="toc-item"><li><span><a href="#多级索引Series" data-toc-modified-id="多级索引Series-2.7.1.1"><span class="toc-item-num">2.7.1.1&nbsp;&nbsp;</span>多级索引Series</a></span></li><li><span><a href="#多级索引高维数据" data-toc-modified-id="多级索引高维数据-2.7.1.2"><span class="toc-item-num">2.7.1.2&nbsp;&nbsp;</span>多级索引高维数据</a></span></li><li><span><a href="#多级索引取值与切片" data-toc-modified-id="多级索引取值与切片-2.7.1.3"><span class="toc-item-num">2.7.1.3&nbsp;&nbsp;</span>多级索引取值与切片</a></span></li><li><span><a href="#多级索引数据累计方法" data-toc-modified-id="多级索引数据累计方法-2.7.1.4"><span class="toc-item-num">2.7.1.4&nbsp;&nbsp;</span>多级索引数据累计方法</a></span></li><li><span><a href="#关于多级索引其他方面的内容" data-toc-modified-id="关于多级索引其他方面的内容-2.7.1.5"><span class="toc-item-num">2.7.1.5&nbsp;&nbsp;</span>关于多级索引其他方面的内容</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#获取Series和DataFrame-基本信息" data-toc-modified-id="获取Series和DataFrame-基本信息-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>获取Series和DataFrame 基本信息</a></span></li><li><span><a href="#缺失值处理" data-toc-modified-id="缺失值处理-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>缺失值处理</a></span></li><li><span><a href="#合并数据集" data-toc-modified-id="合并数据集-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>合并数据集</a></span><ul class="toc-item"><li><span><a href="#通过pd.concat实现简易合并" data-toc-modified-id="通过pd.concat实现简易合并-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>通过pd.concat实现简易合并</a></span></li><li><span><a href="#append()方法" data-toc-modified-id="append()方法-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>append()方法</a></span></li><li><span><a href="#合并与连接" data-toc-modified-id="合并与连接-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>合并与连接</a></span><ul class="toc-item"><li><span><a href="#一对一连接" data-toc-modified-id="一对一连接-5.3.1"><span class="toc-item-num">5.3.1&nbsp;&nbsp;</span>一对一连接</a></span></li><li><span><a href="#多对一" data-toc-modified-id="多对一-5.3.2"><span class="toc-item-num">5.3.2&nbsp;&nbsp;</span>多对一</a></span></li><li><span><a href="#多对多" data-toc-modified-id="多对多-5.3.3"><span class="toc-item-num">5.3.3&nbsp;&nbsp;</span>多对多</a></span></li><li><span><a href="#pd.merge()中参数介绍" data-toc-modified-id="pd.merge()中参数介绍-5.3.4"><span class="toc-item-num">5.3.4&nbsp;&nbsp;</span>pd.merge()中参数介绍</a></span></li></ul></li></ul></li><li><span><a href="#GroupBy：split，apply-and-combine" data-toc-modified-id="GroupBy：split，apply-and-combine-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>GroupBy：split，apply and combine</a></span><ul class="toc-item"><li><span><a href="#初窥" data-toc-modified-id="初窥-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>初窥</a></span></li><li><span><a href="#Groupby-对象" data-toc-modified-id="Groupby-对象-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Groupby 对象</a></span><ul class="toc-item"><li><span><a href="#按列取值" data-toc-modified-id="按列取值-6.2.1"><span class="toc-item-num">6.2.1&nbsp;&nbsp;</span>按列取值</a></span></li><li><span><a href="#按组迭代" data-toc-modified-id="按组迭代-6.2.2"><span class="toc-item-num">6.2.2&nbsp;&nbsp;</span>按组迭代</a></span></li><li><span><a href="#调用方法" data-toc-modified-id="调用方法-6.2.3"><span class="toc-item-num">6.2.3&nbsp;&nbsp;</span>调用方法</a></span></li><li><span><a href="#Groupby对象操作函数aggregate(),filter(),transform(),apply()" data-toc-modified-id="Groupby对象操作函数aggregate(),filter(),transform(),apply()-6.2.4"><span class="toc-item-num">6.2.4&nbsp;&nbsp;</span>Groupby对象操作函数aggregate(),filter(),transform(),apply()</a></span></li></ul></li><li><span><a href="#Groupby更加灵活的分组方式" data-toc-modified-id="Groupby更加灵活的分组方式-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Groupby更加灵活的分组方式</a></span></li><li><span><a href="#一个分组的示例" data-toc-modified-id="一个分组的示例-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>一个分组的示例</a></span></li></ul></li><li><span><a href="#数据透视表" data-toc-modified-id="数据透视表-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>数据透视表</a></span><ul class="toc-item"><li><span><a href="#通过Groupby构建pivot-table" data-toc-modified-id="通过Groupby构建pivot-table-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>通过Groupby构建pivot table</a></span></li><li><span><a href="#pivot_table" data-toc-modified-id="pivot_table-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>pivot_table</a></span></li></ul></li><li><span><a href="#向量化字符串操作" data-toc-modified-id="向量化字符串操作-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>向量化字符串操作</a></span><ul class="toc-item"><li><span><a href="#一些方便的字符串操作方法" data-toc-modified-id="一些方便的字符串操作方法-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>一些方便的字符串操作方法</a></span></li><li><span><a href="#使用正则表达式" data-toc-modified-id="使用正则表达式-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>使用正则表达式</a></span></li><li><span><a href="#其他字符串方法" data-toc-modified-id="其他字符串方法-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>其他字符串方法</a></span></li></ul></li><li><span><a href="#高性能Pandas-eval()与query()" data-toc-modified-id="高性能Pandas-eval()与query()-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>高性能Pandas eval()与query()</a></span><ul class="toc-item"><li><span><a href="#eval()" data-toc-modified-id="eval()-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>eval()</a></span><ul class="toc-item"><li><span><a href="#算术运算" data-toc-modified-id="算术运算-9.1.1"><span class="toc-item-num">9.1.1&nbsp;&nbsp;</span>算术运算</a></span></li><li><span><a href="#使用DataFrame.eval()新增/修改列" data-toc-modified-id="使用DataFrame.eval()新增/修改列-9.1.2"><span class="toc-item-num">9.1.2&nbsp;&nbsp;</span>使用DataFrame.eval()新增/修改列</a></span></li><li><span><a href="#比较运算" data-toc-modified-id="比较运算-9.1.3"><span class="toc-item-num">9.1.3&nbsp;&nbsp;</span>比较运算</a></span></li><li><span><a href="#对象属性与索引" data-toc-modified-id="对象属性与索引-9.1.4"><span class="toc-item-num">9.1.4&nbsp;&nbsp;</span>对象属性与索引</a></span></li><li><span><a href="#通过@符号使用Python局部变量" data-toc-modified-id="通过@符号使用Python局部变量-9.1.5"><span class="toc-item-num">9.1.5&nbsp;&nbsp;</span>通过@符号使用Python局部变量</a></span></li></ul></li><li><span><a href="#query()" data-toc-modified-id="query()-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>query()</a></span></li></ul></li><li><span><a href="#DataFrame的常规操作" data-toc-modified-id="DataFrame的常规操作-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>DataFrame的常规操作</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#重定义列的顺序" data-toc-modified-id="重定义列的顺序-10.0.1"><span class="toc-item-num">10.0.1&nbsp;&nbsp;</span>重定义列的顺序</a></span></li><li><span><a href="#df列名修改" data-toc-modified-id="df列名修改-10.0.2"><span class="toc-item-num">10.0.2&nbsp;&nbsp;</span>df列名修改</a></span></li><li><span><a href="#包含或不包含某个字段" data-toc-modified-id="包含或不包含某个字段-10.0.3"><span class="toc-item-num">10.0.3&nbsp;&nbsp;</span>包含或不包含某个字段</a></span></li></ul></li></ul></li><li><span><a href="#DataFrame数值计算问题" data-toc-modified-id="DataFrame数值计算问题-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>DataFrame数值计算问题</a></span></li><li><span><a href="#Python中创建数组" data-toc-modified-id="Python中创建数组-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Python中创建数组</a></span><ul class="toc-item"><li><span><a href="#使用np.array()从Python列表创建数组" data-toc-modified-id="使用np.array()从Python列表创建数组-12.1"><span class="toc-item-num">12.1&nbsp;&nbsp;</span>使用np.array()从Python列表创建数组</a></span></li><li><span><a href="#从头创建数组" data-toc-modified-id="从头创建数组-12.2"><span class="toc-item-num">12.2&nbsp;&nbsp;</span>从头创建数组</a></span></li></ul></li><li><span><a href="#Numpy数组属性" data-toc-modified-id="Numpy数组属性-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Numpy数组属性</a></span></li><li><span><a href="#Numpy数组索引，切片，重塑" data-toc-modified-id="Numpy数组索引，切片，重塑-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Numpy数组索引，切片，重塑</a></span><ul class="toc-item"><li><span><a href="#基本索引" data-toc-modified-id="基本索引-14.1"><span class="toc-item-num">14.1&nbsp;&nbsp;</span>基本索引</a></span></li><li><span><a href="#花哨的索引" data-toc-modified-id="花哨的索引-14.2"><span class="toc-item-num">14.2&nbsp;&nbsp;</span>花哨的索引</a></span></li><li><span><a href="#关于数组切片非常重要的说明" data-toc-modified-id="关于数组切片非常重要的说明-14.3"><span class="toc-item-num">14.3&nbsp;&nbsp;</span>关于数组切片非常重要的说明</a></span></li><li><span><a href="#数组重塑" data-toc-modified-id="数组重塑-14.4"><span class="toc-item-num">14.4&nbsp;&nbsp;</span>数组重塑</a></span></li></ul></li><li><span><a href="#数组拼接与分裂" data-toc-modified-id="数组拼接与分裂-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>数组拼接与分裂</a></span></li><li><span><a href="#数组计算" data-toc-modified-id="数组计算-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>数组计算</a></span><ul class="toc-item"><li><span><a href="#通用函数" data-toc-modified-id="通用函数-16.1"><span class="toc-item-num">16.1&nbsp;&nbsp;</span>通用函数</a></span><ul class="toc-item"><li><span><a href="#标量与数组之间的基本运算" data-toc-modified-id="标量与数组之间的基本运算-16.1.1"><span class="toc-item-num">16.1.1&nbsp;&nbsp;</span>标量与数组之间的基本运算</a></span></li><li><span><a href="#一些说明" data-toc-modified-id="一些说明-16.1.2"><span class="toc-item-num">16.1.2&nbsp;&nbsp;</span>一些说明</a></span></li><li><span><a href="#聚合" data-toc-modified-id="聚合-16.1.3"><span class="toc-item-num">16.1.3&nbsp;&nbsp;</span>聚合</a></span></li><li><span><a href="#外积" data-toc-modified-id="外积-16.1.4"><span class="toc-item-num">16.1.4&nbsp;&nbsp;</span>外积</a></span></li></ul></li><li><span><a href="#Numpy中的聚合函数" data-toc-modified-id="Numpy中的聚合函数-16.2"><span class="toc-item-num">16.2&nbsp;&nbsp;</span>Numpy中的聚合函数</a></span><ul class="toc-item"><li><span><a href="#求和" data-toc-modified-id="求和-16.2.1"><span class="toc-item-num">16.2.1&nbsp;&nbsp;</span>求和</a></span><ul class="toc-item"><li><span><a href="#一维数组聚合" data-toc-modified-id="一维数组聚合-16.2.1.1"><span class="toc-item-num">16.2.1.1&nbsp;&nbsp;</span>一维数组聚合</a></span></li><li><span><a href="#多维度的聚合" data-toc-modified-id="多维度的聚合-16.2.1.2"><span class="toc-item-num">16.2.1.2&nbsp;&nbsp;</span>多维度的聚合</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#broadcasting-(广播)" data-toc-modified-id="broadcasting-(广播)-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>broadcasting (广播)</a></span><ul class="toc-item"><li><span><a href="#广播介绍" data-toc-modified-id="广播介绍-17.1"><span class="toc-item-num">17.1&nbsp;&nbsp;</span>广播介绍</a></span></li></ul></li><li><span><a href="#比较，掩码与布尔逻辑" data-toc-modified-id="比较，掩码与布尔逻辑-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>比较，掩码与布尔逻辑</a></span><ul class="toc-item"><li><span><a href="#关于布尔数组" data-toc-modified-id="关于布尔数组-18.1"><span class="toc-item-num">18.1&nbsp;&nbsp;</span>关于布尔数组</a></span></li><li><span><a href="#操作布尔数组" data-toc-modified-id="操作布尔数组-18.2"><span class="toc-item-num">18.2&nbsp;&nbsp;</span>操作布尔数组</a></span><ul class="toc-item"><li><span><a href="#统计个数" data-toc-modified-id="统计个数-18.2.1"><span class="toc-item-num">18.2.1&nbsp;&nbsp;</span>统计个数</a></span></li><li><span><a href="#布尔运算符" data-toc-modified-id="布尔运算符-18.2.2"><span class="toc-item-num">18.2.2&nbsp;&nbsp;</span>布尔运算符</a></span></li></ul></li><li><span><a href="#将布尔数组作为掩码" data-toc-modified-id="将布尔数组作为掩码-18.3"><span class="toc-item-num">18.3&nbsp;&nbsp;</span>将布尔数组作为掩码</a></span></li></ul></li></ul></div>

In [2]:
import pandas as pd
import numpy as np
import math

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

> **声明：**

> 以下为个人学习笔记，主要对[Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)，以及Numpy和Pandas官方文档的学习

> 13-18小结为Numpy部分，1-12小结为Pandas部分；可以先熟悉Numpy，再学习Pandas

> 笔记特点，排版随意，措辞极不讲究，容易引起阅读不适，从而放弃入门，当是相信我，你可以找到更好的入门材料

# Pandas 数据导入与导出

## 分隔符分隔的文本文件导入

- 导入csv格式文件(逗号分隔符)

`data = pd.read_csv(filename,header=None,names=[],skiprows=1)`

>参数说明:

>header,默认会将文件第一行作为column names,如果源文件中没有header,设置header=None

>names,通过names参数可以指定column names

>skiprows,指定需要跳过前几行，也有其他的参数用于跳过后面几行

>usecols,指定读取文件中的某些列，e.g.: usecols=['ID','Name'],读取文件中'ID'与'Name'列;usecols=[0,2],读取文件第一列与第三列

- 导入Tab分隔符数据

`data = pd.read_table()`


In [5]:
pd.read_csv('test.csv',usecols=['A','C'])

A  C
0  1  3
1  4  6
2  7  9

## 基于URL链接从网页解析导入表格数据

In [4]:
import requests
import lxml
import html5lib

In [52]:
f_states =   pd.read_html('https://simple.wikipedia.org/wiki/List_of_U.S._states')

In [53]:
#取出第一个表格
f_states[0].head(5)

0             1           2            3                  4
0  Sl no.  Abbreviation  State Name      Capital     Became a State
1       1            AL     Alabama   Montgomery  December 14, 1819
2       2            AK      Alaska       Juneau    January 3, 1959
3       3            AZ     Arizona      Phoenix  February 14, 1912
4       4            AR    Arkansas  Little Rock      June 15, 1836

In [57]:
my_columns = f_states[0].loc[0]
copy_df = f_states[0][1:]
copy_df.columns = my_columns
copy_df.head(5)

0 Sl no. Abbreviation  State Name      Capital     Became a State
1      1           AL     Alabama   Montgomery  December 14, 1819
2      2           AK      Alaska       Juneau    January 3, 1959
3      3           AZ     Arizona      Phoenix  February 14, 1912
4      4           AR    Arkansas  Little Rock      June 15, 1836
5      5           CA  California   Sacramento  September 9, 1850

## 导入系统剪贴板中的数据

In [25]:
cp_df = pd.read_clipboard(header=None,names=['GEO_id'])
cp_df

GEO_id
0  GSE33265
1  GSE98924
2  GSE81069
3  GSE86272

## 数据导出

- 导出为csv格式的文件

    df.to_csv(filename)

当然其他格式，比如excel,json等都可以导出


# Pandas DataFrame数据选择（切片与其他数据获得方式）

- 使用基本[]索引数据
- 使用.列名索引数据
- 使用.loc()方法索引数据
- 使用.iloc()方法索引数据
- .isin()过滤筛选
- .query()
- .str.contains()使用正则表达式匹配过滤

## 用于测试的数据

In [6]:
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})
# 重置索引
df.index = ['LOC_a','LOC_b','c']
df

A  B  C
LOC_a  1  4  7
LOC_b  2  5  8
c      3  6  9

## 使用[]索引数据

### 列索引

In [33]:
# 单列索引，返回Series
df['A']

LOC_a    1
LOC_b    2
c        3
Name: A, dtype: int64

In [19]:
# 多列索引，返回DataFrame
df[['A','B']]

A  B
LOC_a  1  4
LOC_b  2  5
c      3  6

### 行索引

In [27]:
#第二行到最后
df[1:]

A  B  C
LOC_b  2  5  8
c      3  6  9

In [29]:
#取第一行
df[1:2]

A  B  C
LOC_b  2  5  8

## 使用.列名索引列数据

In [30]:
#索引某列，返回Series
df.A

LOC_a    1
LOC_b    2
c        3
Name: A, dtype: int64

## 使用.loc()方法索引数据

In [9]:
#.loc() 按名称索引,返回Series
df.loc[:,'A']

LOC_a    1
LOC_b    2
c        3
Name: A, dtype: int64

In [31]:
#选择多列
df.loc[:,['A','C']]

A  C
LOC_a  1  7
LOC_b  2  8
c      3  9

In [33]:
#基于index选择某行
df.loc['c']

A    3
B    6
C    9
Name: c, dtype: int64

In [14]:
df.loc[['LOC_a','c'],:]

A  B  C
LOC_a  1  4  7
c      3  6  9

## 使用.iloc()方法索引数据

In [15]:
# 下面方法与df.loc['c']等价
df.iloc[2]

A    3
B    6
C    9
Name: c, dtype: int64

In [17]:
#.iloc()按位置序列索引
df.iloc[:,1]

LOC_a    4
LOC_b    5
c        6
Name: B, dtype: int64

In [18]:
df.iloc[[0,2],2]

LOC_a    7
c        9
Name: C, dtype: int64

In [34]:
#索引值
df.iloc[1,2]

8

## 条件过滤索引

### .loc[]条件过滤

In [36]:
df.loc[df.A < 2] #等价于df.loc[df.A < 2,:]

A  B  C
LOC_a  1  4  7

In [37]:
df.loc[df.A < 2,'A']

LOC_a    1
Name: A, dtype: int64

In [38]:
df.loc[df.A < 2,['A','C']]

A  C
LOC_a  1  7

In [40]:
# 多条件,与
df.loc[(df.A > 2) & (df.C>7)]

A  B  C
c  3  6  9

In [42]:
#多条件,或
df.loc[(df.A > 2) | (df.C>7)]

A  B  C
LOC_b  2  5  8
c      3  6  9

### .str.contains()使用正则表达式匹配过滤

In [44]:
#index包含LOC字符串的所有行
df[df.index.str.contains(r'LOC')]

A  B  C
LOC_a  1  4  7
LOC_b  2  5  8

In [46]:
df[df.index.str.contains(r'LOC')]

A  B  C
LOC_a  1  4  7
LOC_b  2  5  8

### 使用query()条件过滤

In [47]:
df.query("A>=2 & (B>=4 | C>=7)")

A  B  C
LOC_b  2  5  8
c      3  6  9

## 层级索引

### 多级索引Series

> 元组表示是多级索引的基础

#### 多级索引Series

In [25]:
# 创建多级索引最直接的办法就是将index参数设置为至少二维的索引数组
CT = pd.Series([0.1,0.2,0.3,0.4],index = [['a','a','b','b'],[1,2,1,2]])
CT

a  1    0.1
   2    0.2
b  1    0.3
   2    0.4
dtype: float64

In [31]:
# 将以元组作为键的字典传递给Pandas会默认转化为MultiIndex
data = {('Jiawen',2006):3,
        ('Jiawen',2007):5,
        ('oocarain',2006):2,
        ('oocarain',2007):6}
score = pd.Series(data)
score

Jiawen    2006    3
          2007    5
oocarain  2006    2
          2007    6
dtype: int64

In [33]:
# 显式创建多级索引
# 从数据构建
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [34]:
# 从元组构建
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [36]:
# 两个索引笛卡尔积
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [32]:
# 为多级索引创建等级名称
score.index.names= ['Name','Years']
score

Name      Years
Jiawen    2006     3
          2007     5
oocarain  2006     2
          2007     6
dtype: int64

#### 多级索引高维数据

In [61]:
# unstack将多级索引Series转化为DataFrame
CT_df = CT.unstack(level = 0)
CT_df

a    b
1  0.1  0.3
2  0.2  0.4

In [62]:
CT_df = CT.unstack(level = 1)
CT_df

1    2
a  0.1  0.2
b  0.3  0.4

In [27]:
# stack()实现希相反的效果
CT_df.stack()

a  1    0.1
   2    0.2
b  1    0.3
   2    0.4
dtype: float64

In [29]:
# 多级索引每增加一级，就表示数据增加一维
CT_tri = pd.DataFrame({'Weight':CT,'Height':[2,1,3,1]})
CT_tri

Height  Weight
a 1       2     0.1
  2       1     0.2
b 1       3     0.3
  2       1     0.4

In [38]:
# 多级列索引
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
columns = pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']],names=['subject','type'])

In [42]:
data = np.round(np.random.randn(4,6),1)
data[:,::2] *= 10
data += 37
data

array([[43. , 36.7, 42. , 36.6, 47. , 38. ],
       [38. , 38.4, 37. , 37.3, 37. , 36.9],
       [49. , 36.6, 47. , 38.6, 37. , 34.5],
       [33. , 35.5, 41. , 36. , 40. , 35. ]])

In [43]:
health_data = pd.DataFrame(data,index=index,columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      43.0  36.7  42.0  36.6  47.0  38.0
     2      38.0  38.4  37.0  37.3  37.0  36.9
2014 1      49.0  36.6  47.0  38.6  37.0  34.5
     2      33.0  35.5  41.0  36.0  40.0  35.0

#### 多级索引取值与切片

In [48]:
score['Jiawen',2006]

3

In [49]:
score['Jiawen']

Years
2006    3
2007    5
dtype: int64

In [50]:
score.loc['Jiawen':'oocarain']

Name      Years
Jiawen    2006     3
          2007     5
oocarain  2006     2
          2007     6
dtype: int64

In [51]:
# 用较低层级的索引取值，第一层级的索引可以用空切片
score[:,2006]

Name
Jiawen      3
oocarain    2
dtype: int64

In [52]:
# 布尔掩码索取
score[score > 2]

Name      Years
Jiawen    2006     3
          2007     5
oocarain  2007     6
dtype: int64

In [53]:
# 花哨索引
score[['Jiawen','oocarain']]

Name      Years
Jiawen    2006     3
          2007     5
oocarain  2006     2
          2007     6
dtype: int64

In [55]:
health_data['Guido','HR']

year  visit
2013  1        42.0
      2        37.0
2014  1        47.0
      2        41.0
Name: (Guido, HR), dtype: float64

In [58]:
health_data.iloc[:2,:2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      43.0  36.7
     2      38.0  38.4

In [59]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        43.0
      2        38.0
2014  1        49.0
      2        33.0
Name: (Bob, HR), dtype: float64

In [60]:
# 对于指定行列索引，下面的方法较为方便
idx = pd.IndexSlice
health_data.loc[idx[:,2], idx[:,'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 2      38.0  37.0  37.0
2014 2      33.0  41.0  40.0

#### 多级索引数据累计方法

In [75]:
data_mean = health_data.mean(level='year')
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     40.5  37.55  39.5  36.95  42.0  37.45
2014     41.0  36.05  44.0  37.30  38.5  34.75

In [76]:
data_mean.mean(axis=1,level='type')

type         HR       Temp
year                      
2013  40.666667  37.316667
2014  41.166667  36.033333

#### 关于多级索引其他方面的内容

In [63]:
# 在进行多级索引切片操作的时候，要确保MultiIndex是有序的索引，不然会报错
index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data = pd.Series(np.random.rand(6),index=index)
data.index.names = ['char','int']
data

char  int
a     1      0.077166
      2      0.148684
c     1      0.986469
      2      0.971176
b     1      0.538503
      2      0.738909
dtype: float64

In [65]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [67]:
data = data.sort_index()
data

char  int
a     1      0.077166
      2      0.148684
b     1      0.538503
      2      0.738909
c     1      0.986469
      2      0.971176
dtype: float64

In [69]:
data['a':'b']

char  int
a     1      0.077166
      2      0.148684
b     1      0.538503
      2      0.738909
dtype: float64

In [70]:
# 索引设置与重置
score

Name      Years
Jiawen    2006     3
          2007     5
oocarain  2006     2
          2007     6
dtype: int64

In [71]:
# 将多层级索引Series转化为DataFrame
score_flat = score.reset_index(name='scores')
score_flat

Name  Years  scores
0    Jiawen   2006       3
1    Jiawen   2007       5
2  oocarain   2006       2
3  oocarain   2007       6

In [73]:
# 结果是带多级索引的DataFrame
score_flat.set_index(['Name','Years'])

scores
Name     Years        
Jiawen   2006        3
         2007        5
oocarain 2006        2
         2007        6

pandas.core.frame.DataFrame

# 获取Series和DataFrame 基本信息

- 查看index，数据类型
    df.info()
- 查看描述性的统计信息
    df.describe()
- 查看数据出现频数
    df.A.value_counts()
  

In [49]:
# 查看df中数据类型，是否存在缺失值，non-null表示不存在缺失值
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, LOC_a to c
Data columns (total 3 columns):
A    3 non-null int64
B    3 non-null int64
C    3 non-null int64
dtypes: int64(3)
memory usage: 176.0+ bytes


In [50]:
# df每列的基本统计信息
df.describe()

A    B    C
count  3.0  3.0  3.0
mean   2.0  5.0  8.0
std    1.0  1.0  1.0
min    1.0  4.0  7.0
25%    1.5  4.5  7.5
50%    2.0  5.0  8.0
75%    2.5  5.5  8.5
max    3.0  6.0  9.0

In [51]:
# 查看df中所包含的数据总量，即：行*列
df.size

9

In [54]:
# 查看df的column name
df.columns.values

array(['A', 'B', 'C'], dtype=object)

In [56]:
# 查看df的行数，这儿通过df的index的size属性查看
# df.columns.size查看列数
df.index.size

3

In [64]:
# 查看某列元素出现的次数，下面可以看到在df中1，2，3分别出现1次
df.A.value_counts()

3    1
2    1
1    1
Name: A, dtype: int64

# 缺失值处理

> 由于电脑自动重启，笔记此部分未保存，导致内心极度不适，故不再重写此部分了，哈哈哈，符合缺失主题

- isnull()
- notnull()
- dropna()
- fillna()

# 合并数据集

## 通过pd.concat实现简易合并

In [77]:
ser1 = pd.Series(['A','B','C'], index=[1,2,3])
ser2 = pd.Series(['D','E','F'], index = [4,5,6])
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [78]:
# DataFrame的合并也是一样的
df1 = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df2 = pd.DataFrame({'A':[7,8,9],'B':[10,11,12]})
pd.concat([df1,df2])

A   B
0  1   4
1  2   5
2  3   6
0  7  10
1  8  11
2  9  12

In [83]:
df3 = pd.DataFrame({'A':[2,1,3],'C':[3,5,7]})

In [80]:
# 可以看到上面index重复，可通过ignore_index参数忽略
pd.concat([df1,df2],ignore_index=True)

A   B
0  1   4
1  2   5
2  3   6
3  7  10
4  8  11
5  9  12

In [82]:
# 对于重复索引的另外一个解决办法是多级索引
pd.concat([df1,df2],keys=['x','y'])

A   B
x 0  1   4
  1  2   5
  2  3   6
y 0  7  10
  1  8  11
  2  9  12

In [79]:
pd.concat([df1,df2],axis=1)

A  B  A   B
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

In [84]:
# 对于列名部分相同的情况
pd.concat([df1,df3])

A    B    C
0  1  4.0  NaN
1  2  5.0  NaN
2  3  6.0  NaN
0  2  NaN  3.0
1  1  NaN  5.0
2  3  NaN  7.0

In [86]:
# 通过join参数调整
pd.concat([df1,df3],join='inner',ignore_index=True)

A
0  1
1  2
2  3
3  2
4  1
5  3

In [96]:
# join_axes指定合并输出的列
pd.concat([df1,df3],join_axes=[pd.Index(['A','C'])],ignore_index=True)

A    C
0  1  NaN
1  2  NaN
2  3  NaN
3  2  3.0
4  1  5.0
5  3  7.0

## append()方法

In [97]:
# 个人建议还是使用concat
df1.append(df2)

A   B
0  1   4
1  2   5
2  3   6
0  7  10
1  8  11
2  9  12

## 合并与连接

> pd.merge()的功能全解

### 一对一连接

In [98]:
df1 = pd.DataFrame({'employee':['Bob','Jake','Lisa','Sue'],
                    'group':['Accounting','Engineering','Engineering','HR']})
df2 = pd.DataFrame({'employee':['Lisa','Bob','Jake','Sue'],
                    'hire_data':[2004,2008,2012,2014]})

In [99]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [100]:
df2

employee  hire_data
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [101]:
df3 = pd.merge(df1,df2)
df3

employee        group  hire_data
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

### 多对一

In [102]:
df4 = pd.DataFrame({'group':['Accounting','Engineering','HR'],
                   'supervisor':['Carly','Guido','Steve']})
pd.merge(df3,df4)

employee        group  hire_data supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

### 多对多

In [103]:
df5 = pd.DataFrame({'group':['Accounting','Accounting','Engineering','Engineering','HR','HR'],
                    'skills':['math','spreadsheets','coding','linux','spreadsheets','organization']})
pd.merge(df1,df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

### pd.merge()中参数介绍

将讨论一下参数与方法
- on
- left_on right_on
- left_index right_index df1.join(df2)
- how
- suffixes

In [121]:
football = pd.DataFrame({'name':['Jiawen','Bingqian','oocarain','paprica'],
                         'score':[2,3,1,2]})
basketball1 = pd.DataFrame({'name':['Jiawen','Frozoto1','Bingqian','paprica','superjw'],
                           'score':[2,4,1,5,3]})
basketball2 = pd.DataFrame({'username':['Jiawen','Frozoto1','Bingqian','paprica','superjw'],
                           'score':[2,4,1,5,3]})

In [109]:
# on指定合并依赖的列，suffixes为重复列名添加后缀索引，以示区分
pd.merge(football,basketball1,on='name',suffixes=['_football','_basketball'])

name  score_football  score_basketball
0    Jiawen               2                 2
1  Bingqian               3                 1
2   paprica               2                 5

In [110]:
# on可以选取多个条目作为merge条件
AA = pd.DataFrame({'name':['A','B','C'],
                  'id':[1,2,3],
                  'score':[0.1,0.2,0.3]})
BB = pd.DataFrame({'name':['A','C','D'],
                  'id':[1,3,4],
                  'hight':[0.5,0.6,0.4]})

In [111]:
pd.merge(AA,BB,on=['name','id'])

id name  score  hight
0   1    A    0.1    0.5
1   3    C    0.3    0.6

In [113]:
# 当列名不相同，但是其表述的含义是一样，想用它们作merge条件的时候，可以使用left_on和right_on，但是输出结果中会有多余的一列条目，
#可以通过drop()去除
pd.merge(football,basketball2,left_on='name',right_on='username',suffixes=['_football','_basketball']).drop('name',axis=1)

score_football  score_basketball  username
0               2                 2    Jiawen
1               3                 1  Bingqian
2               2                 5   paprica

In [114]:
footballA = football.set_index('name')
basketball1A = basketball1.set_index('name')

In [115]:
footballA

score
name           
Jiawen        2
Bingqian      3
oocarain      1
paprica       2

In [116]:
basketball1A

score
name           
Jiawen        2
Frozoto1      4
Bingqian      1
paprica       5
superjw       3

In [117]:
# 基于index名称merge. 另外，不加suffixes指定后缀，将会使用默认的'_x'和'_y'
pd.merge(footballA,basketball1A,left_index=True,right_index=True)

score_x  score_y
name                      
Jiawen          2        2
Bingqian        3        1
paprica         2        5

In [131]:
# 对于可以使用index去merge的pandas对象，可以快速的使用join()方法
footballA.join(basketball1A,lsuffix='_f',rsuffix='_b')

score_f  score_b
name                      
Jiawen          2      2.0
Bingqian        3      1.0
oocarain        1      NaN
paprica         2      5.0

In [118]:
# left_index与right_on 或 left_on与right_index混用
pd.merge(football,basketball1A,left_on='name',right_index=True)

name  score_x  score_y
0    Jiawen        2        2
1  Bingqian        3        1
3   paprica        2        5

In [119]:
pd.merge(footballA,basketball1,left_index=True,right_on='name')

score_x      name  score_y
0        2    Jiawen        2
2        3  Bingqian        1
3        2   paprica        5

In [125]:
# 设置数据连接的集合操作规则
# 默认连接方式为inner, 即， how='inner', 内连接 ，取共有
pd.merge(football,basketball1,on='name',how='inner')

name  score_x  score_y
0    Jiawen        2        2
1  Bingqian        3        1
2   paprica        2        5

In [126]:
# how='outer' 外连接 
pd.merge(football,basketball1,on='name',how='outer')

name  score_x  score_y
0    Jiawen      2.0      2.0
1  Bingqian      3.0      1.0
2  oocarain      1.0      NaN
3   paprica      2.0      5.0
4  Frozoto1      NaN      4.0
5   superjw      NaN      3.0

In [132]:
# how='left' 或 how='right'
pd.merge(football,basketball1,on='name',how='left')

name  score_x  score_y
0    Jiawen        2      2.0
1  Bingqian        3      1.0
2  oocarain        1      NaN
3   paprica        2      5.0

In [133]:
pd.merge(football,basketball1,on='name',how='right')

name  score_x  score_y
0    Jiawen      2.0        2
1  Bingqian      3.0        1
2   paprica      2.0        5
3  Frozoto1      NaN        4
4   superjw      NaN        3

# GroupBy：split，apply and combine

## 初窥

> group by "分组"；其理念为 分割（split）,应用（apply）,组合（combine）

为了很好的理解上面的概念，我们可以先看下面图示，然后结合例子

![](https://i.loli.net/2018/11/19/5bf2631aa4ef7.png)

In [136]:
df = pd.DataFrame({'key':['A','B','C','A','B','C'],
                   'data': range(6)}, columns =['key','data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [137]:
# groupby()返回的不是DataFrame对象，而是DataFrameGroupBy对象, 在应用到累计函数之前不会计算， 这种“延迟计算”在实际使用中
# 非常高效
df.groupby('key')

In [138]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

## Groupby 对象

### 按列取值

In [139]:
planets = sns.load_dataset('planets')
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [142]:
# Groupby对象也支持按列取值，为了方便理解，可以把Groupby对象看成是DataFrame的集合
planets.groupby('method')['orbital_period']

In [141]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

### 按组迭代

In [146]:
for (method,group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method,group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)


### 调用方法

In [150]:
planets.groupby('method')['distance'].describe()

count         mean          std      min  \
method                                                                    
Astrometry                       2.0    17.875000     4.094148    14.98   
Eclipse Timing Variations        4.0   315.360000   213.203907   130.72   
Imaging                         32.0    67.715937    53.736817     7.69   
Microlensing                    10.0  4144.000000  2076.611556  1760.00   
Orbital Brightness Modulation    2.0  1180.000000     0.000000  1180.00   
Pulsar Timing                    1.0  1200.000000          NaN  1200.00   
Pulsation Timing Variations      0.0          NaN          NaN      NaN   
Radial Velocity                530.0    51.600208    45.559381     1.35   
Transit                        224.0   599.298080   913.876990    38.00   
Transit Timing Variations        3.0  1104.333333   915.819487   339.00   

                                     25%       50%        75%      max  
method                                                                  
Astrometry                       16.4275    17.875    19.3225    20.77  
Eclipse Timing Variations       130.7200   315.360   500.0000   500.00  
Imaging                          22.1450    40.395   132.6975   165.00  
Microlensing                   2627.5000  3840.000  4747.5000  7720.00  
Orbital Brightness Modulation  1180.0000  1180.000  1180.0000  1180.00  
Pulsar Timing                  1200.0000  1200.000  1200.0000  1200.00  
Pulsation Timing Variations          NaN       NaN        NaN      NaN  
Radial Velocity                  24.4125    40.445    59.2175   354.00  
Transit                         200.0000   341.000   650.0000  8500.00  
Transit Timing Variations       597.0000   855.000  1487.0000  2119.00

### Groupby对象操作函数aggregate(),filter(),transform(),apply()

In [154]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key':['A','B','C','A','B','C'],
                   'data1': range(6),
                   'data2': rng.randint(0,10,6)},
                    columns = ['key','data1','data2'])
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [155]:
df.groupby('key').aggregate(['min',np.median, max])

data1            data2           
      min median max   min median max
key                                  
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [156]:
# 通过字典指定每列需要累计的函数
df.groupby('key').aggregate({'data1':'min','data2':'max'})

data1  data2
key              
A        0      5
B        1      7
C        2      9

In [157]:
# 过滤
def filter_fun(x):
    return x['data2'].std() > 4

In [158]:
# filter接受一个callable对象
df.groupby('key').filter(filter_fun)

key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9

In [163]:
# 转换
df.groupby('key').transform(lambda x: x- x.mean())

data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

In [164]:
# apply()方法
def norm_by_data2(x):
    x['data1'] /= x['data2'].sum()
    return x

In [165]:
df.groupby('key').apply(norm_by_data2)

key     data1  data2
0   A  0.000000      5
1   B  0.142857      0
2   C  0.166667      3
3   A  0.375000      3
4   B  0.571429      7
5   C  0.416667      9

## Groupby更加灵活的分组方式

In [168]:
## 设置Groupby()分割键
L= [0,1,0,1,2,0]
df.groupby(L).sum()
# 这个需要解释一下：
# L 共分成了三组，分别是，0，1，2
# 对应如下：
# 0 1 0  1 2  0    <-- 新的分组列表
# |   |  |   |  |   |
#A  B C A B  C    <-- key
#0  1  2  3 4  5    <-- index
# 所以0组对应为0A 2C 5C三行
# 1组对应为1B 3A两行
# 2 组对应为4B这一行

data1  data2
0      7     17
1      4      3
2      4      7

In [169]:
## 用字典或Series将索引映射到分组名
df2 = df.set_index('key')
mapping = {'A':'new_A','B':'new_B','C':'new_B'}
df2.groupby(mapping).sum()

data1  data2
new_A      3      8
new_B     12     19

In [177]:
df2

data1  data2
key              
A        0      5
B        1      0
C        2      3
A        3      3
B        4      7
C        5      9

In [178]:
# 将任意Python函数传入groupby, 函数映射索引，然后新的分组输出
df2.groupby(str.lower).mean()

data1  data2
a    1.5    4.0
b    2.5    3.5
c    3.5    6.0

In [179]:
# 多个有效键组合
df2.groupby([str.lower,mapping]).mean()

data1  data2
a new_A    1.5    4.0
b new_B    2.5    3.5
c new_B    3.5    6.0

## 一个分组的示例

In [199]:
# 计算年份的年代值
decade = 10 * (planets['year'] // 10)
# 修改数据类型，并在字符串末尾添加's'
decade = decade.astype(str) + 's'
# 
decade.name = 'decade'
#
planets.groupby(['method',decade])['number'].sum().unstack().fillna(0)

decade                         1980s  1990s  2000s  2010s
method                                                   
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0

# 数据透视表

> 数据透视表是与Groupy类似的操作，只不过数据透视表的split-apply-combine是同时发生在二维网格上的（行列同时分组）

## 通过Groupby构建pivot table

In [201]:
titanic = sns.load_dataset('titanic')

In [203]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [205]:
titanic.groupby(['sex','class'])['survived'].aggregate('mean').unstack()
# 由于二维Groupby应用场景普遍，为解决上面的问题，Pandas提供了pivot_table()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

## pivot_table

In [208]:
titanic.pivot_table('survived',index='sex',columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [210]:
# 多级透视
age = pd.cut(titanic['age'],[0,18,80])
titanic.pivot_table('survived',['sex',age],'class')

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [211]:
# pd.qcut 将船票价格按照计数项等分成两份
fare = pd.qcut(titanic['fare'],2)
titanic.pivot_table('survived',['sex',age],['class',fare])

class                      First                             Second  \
fare            (-0.001, 14.454] (14.454, 512.329] (-0.001, 14.454]   
sex    age                                                            
female (0, 18]               NaN          0.909091         1.000000   
       (18, 80]              NaN          0.972973         0.880000   
male   (0, 18]               NaN          0.800000         0.000000   
       (18, 80]              0.0          0.391304         0.098039   

class                                        Third                    
fare            (14.454, 512.329] (-0.001, 14.454] (14.454, 512.329]  
sex    age                                                            
female (0, 18]           1.000000         0.714286          0.318182  
       (18, 80]          0.914286         0.444444          0.391304  
male   (0, 18]           0.818182         0.260870          0.178571  
       (18, 80]          0.030303         0.125000          0.192308

> pivot_table方法的完整签名

`DataFrame.pivot_table(values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')`

- aggfunc 用于设置累计函数类型，默认是mean, 与Groupby一样累计函数可以用字符串'mean','max','min','sum'等表示，
  也可以用标准的累计函数np.sum(),min(),sum(),还可以通过字典为不同的列指明不同的累计函数
- fill_value ,dropna 用于处理存在的缺失值
- margins, 计算每组总数

In [216]:
titanic.pivot_table(index='sex', columns='class', aggfunc={'survived':'sum','fare':'mean'})
# 这里忽略了参数values,因为当我们为aggfunc指定映射关系的时候，待透视的数值就已经确定了

fare                       survived             
class        First     Second      Third    First Second Third
sex                                                           
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [217]:
# 计算每一组的总数
titanic.pivot_table('survived','sex','class',margins=True)

class      First    Second     Third       All
sex                                           
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

# 向量化字符串操作

## 一些方便的字符串操作方法

> Numpy，在操作纯数组数据时很有优势，但是其并未为字符串数组提供简单的接口。而Pandas为包含Series和Index对象提供str属性,
> 在处理字符串很方便

In [4]:
names = pd.Series(['OoincaRain LL','jiaWen HH','PapriKa VV',None,'oBingqian QQ'])
names.str.capitalize()

0    Ooincarain ll
1        Jiawen hh
2       Paprika vv
3             None
4     Obingqian qq
dtype: object

In [253]:
names.str.startswith('o')

0    False
1    False
2    False
3     None
4     True
dtype: object

> Pandas的str方法借鉴了Python字符串的许多方法，但是存在些许异同

## 使用正则表达式

In [254]:
names.str.match(r'jiaWen')

0    False
1     True
2    False
3     None
4    False
dtype: object

In [255]:
names.str.extract(r'([A-Za-z]+)')

d:\biosoft\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """Entry point for launching an IPython kernel.


0    OoincaRain
1        jiaWen
2       PapriKa
3           NaN
4     oBingqian
dtype: object

In [256]:
names.str.findall(r'^[OP].*[^ab]$')

0    [OoincaRain LL]
1                 []
2       [PapriKa VV]
3               None
4                 []
dtype: object

In [257]:
names.str.replace(r'[H]+','OO')

0    OoincaRain LL
1        jiaWen OO
2       PapriKa VV
3             None
4     oBingqian QQ
dtype: object

In [258]:
repl = lambda m: m.group(0)[::-1]
names.str.replace(r'.*',repl)

0    LL niaRacnioO
1        HH neWaij
2       VV aKirpaP
3             None
4     QQ naiqgniBo
dtype: object

In [250]:
names.str.contains(r'in')

0     True
1    False
2    False
3     None
4     True
dtype: object

In [259]:
names.str.count(r'in')

0    2.0
1    0.0
2    0.0
3    NaN
4    1.0
dtype: float64

In [261]:
names.str.split(r'in')

0    [Oo, caRa,  LL]
1        [jiaWen HH]
2       [PapriKa VV]
3               None
4     [oB, gqian QQ]
dtype: object

> 将正则表达式应用到Series和DataFrame之中，可以方便的实现数据清洗

下面列出Pandas向量化字符串方法与Python re正则模块函数的对应关系:

    match()	Call re.match() on each element, returning a boolean.
    extract()	Call re.match() on each element, returning matched groups as strings.
    findall()	Call re.findall() on each element
    replace()	Replace occurrences of pattern with some other string
    contains()	Call re.search() on each element, returning a boolean
    count()	Count occurrences of pattern
    split()	Equivalent to str.split(), but accepts regexps
    rsplit()	Equivalent to str.rsplit(), but accepts regexps

## 其他字符串方法

- slice()
- get()
- cat()
- pad()
- repeat()
- join()
- get_dummies()

In [265]:
names.str.slice(0,3) #等价于names.str[0:3]

0     Ooi
1     jia
2     Pap
3    None
4     oBi
dtype: object

In [269]:
names.str.split().str.get(-1)

0      LL
1      HH
2      VV
3    None
4      QQ
dtype: object

In [7]:
names.str.cat(sep='|')

'OoincaRain LL|jiaWen HH|PapriKa VV|oBingqian QQ'

In [28]:
# 用分隔符链接每个元素
names.str.join('-')

0    O-o-i-n-c-a-R-a-i-n- -L-L
1            j-i-a-W-e-n- -H-H
2          P-a-p-r-i-K-a- -V-V
3                         None
4      o-B-i-n-g-q-i-a-n- -Q-Q
dtype: object

In [30]:
names.str.repeat(2)

0    OoincaRain LLOoincaRain LL
1            jiaWen HHjiaWen HH
2          PapriKa VVPapriKa VV
3                          None
4      oBingqian QQoBingqian QQ
dtype: object

In [10]:
names.str.cat(['A','B','C','D','E'],sep=',')

0    OoincaRain LL,A
1        jiaWen HH,B
2       PapriKa VV,C
3                NaN
4     oBingqian QQ,E
dtype: object

In [13]:
pd.Series(['a','b']).str.cat([['x','y'],['1','2']],sep=',')

0    a,x,1
1    b,y,2
dtype: object

In [17]:
# 在字符串左右或两侧添加空格，width指定字符串的固定宽度
names.str.pad(width=6)

0    OoincaRain LL
1        jiaWen HH
2       PapriKa VV
3             None
4     oBingqian QQ
dtype: object

In [20]:
# fillchar指明填充的字符串，默认为空格
names.str.pad(width=13, fillchar='=')

0    OoincaRain LL
1    ====jiaWen HH
2    ===PapriKa VV
3             None
4    =oBingqian QQ
dtype: object

In [21]:
# side可以为leaf , right , both；指明填充的位置
names.str.pad(width=13, fillchar='=',side='both')

0    OoincaRain LL
1    ==jiaWen HH==
2    ==PapriKa VV=
3             None
4    =oBingqian QQ
dtype: object

In [31]:
# str.get_dummies实现按照分隔符提取每个元素的dummy变量，转换为独热（one-hot）编码的DataFrame
# 考虑这样的情况：
# A = 喜欢篮球 ；B = 喜欢足球 ； C = 喜欢动漫 ; D = 喜欢游戏
hobby = pd.Series(['B|C|D','B|D','A|C','B|D','B|C','B|C|D'])
hobby.str.get_dummies('|')

A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  0  1  0  1
4  0  1  1  0
5  0  1  1  1

# 高性能Pandas eval()与query()

> Pandas的eval() 和 query()工具是基于Numexpr实现的字符串代数式，优点是内存消耗少，运行速度快

## eval()

### 算术运算

In [38]:
# pd.eval()支持所有的算术运算
df1 = pd.DataFrame(np.random.randint(0,9,size=(3,4)),columns=['A','B','C','D'])
df2 = pd.DataFrame(np.random.randint(0,9,size=(3,4)),columns=['A','B','C','D'])

In [39]:
df1

A  B  C  D
0  6  7  6  8
1  4  0  8  5
2  6  3  2  1

In [40]:
df2 

A  B  C  D
0  0  4  8  0
1  8  1  1  7
2  2  4  8  0

In [41]:
pd.eval('df1 + df2')

A   B   C   D
0   6  11  14   8
1  12   1   9  12
2   8   7  10   1

In [42]:
# 计算结果是相同的
np.allclose(df1 + df2 , pd.eval('df1 + df2'))

True

In [62]:
pd.eval("df1.A + df2.B")

0    10
1     5
2    10
dtype: int32

In [64]:
# DataFrame.eval() 方法可以直接使用列名
df1.eval(" (A - B) / (C - 1)")

0   -0.200000
1    0.571429
2    3.000000
dtype: float64

### 使用DataFrame.eval()新增/修改列

In [65]:
# 新增
df1.eval(" E = (A + B) * C",inplace=True)
df1

A  B  C  D   E
0  6  7  6  8  78
1  4  0  8  5  32
2  6  3  2  1  18

In [66]:
# 修改
df1.eval(" E = (A - B) * C",inplace=True)
df1

A  B  C  D   E
0  6  7  6  8  -6
1  4  0  8  5  32
2  6  3  2  1   6

### 比较运算

In [44]:
nrows , ncols = 100000,100
rng = np.random.RandomState(42)
dfa, dfb ,dfc, dfd = (pd.DataFrame(rng.rand(nrows,ncols)) for i in range(4))

In [45]:
result1 = (dfa < dfb) & (dfb <= dfc) & (dfc != dfd)
result2 = pd.eval('dfa < dfb <= dfc != dfd') # 更倾向数学表达的简洁性
np.allclose(result1,result2)

True

In [47]:
###位运算符 &（与） 和 | （或）的使用
result1 = (dfa < 0.5) & (dfb < 0.5) | (dfc < dfd)
result2 = pd.eval('(dfa < 0.5) & (dfb < 0.5) | (dfc < dfd)')
np.allclose(result1,result2)

True

In [50]:
# 使用and 和 or 也是可以的
result3 = pd.eval('(dfa < 0.5) and (dfb < 0.5) or (dfc < dfd)')
np.allclose(result3,result2)

True

### 对象属性与索引

In [61]:
pd.eval('dfb.T[0] + dfc.iloc[1]').head()

0    1.502505
1    0.439865
2    1.192271
3    0.936217
4    1.037423
dtype: float64

### 通过@符号使用Python局部变量

In [69]:
# @符号表示：“这是一个变量名称而不是一个列名称”，从而我们可以灵活的使用列名称的命名空间和Python对象命名空间这两个“命名空间”
# @符号只能在DataFrame.eval()中使用，而不能在pandas.eval()函数中使用，因为pandas.eval()只能获取一个命名空间的内容
column_mean = df1.mean(1)
df1.eval('A + @column_mean')

0    10.2
1    13.8
2     9.6
dtype: float64

## query()

In [76]:
C_mean = df2.C.mean()
df2.query('A < @C_mean and B < @C_mean')

A  B  C  D
0  0  4  8  0
2  2  4  8  0

# DataFrame的常规操作

### 重定义列的顺序

> 当我们在进行某些操作(比如merge之类的)之后得到的df的列排列的顺序并不是我们想要的，或者我们对得到的df的列顺序并不满意想做修改
> 以下可以解决这个问题

In [3]:
df_a = pd.DataFrame({'chrom':['Chr1','Chr1','Chr2','Chr2'],
                     'spos':[1,5,2,9],'epos':[3,14,7,20],'lev':[0.1,0.2,0.3,0.4]})
df_b = pd.DataFrame({'chrom':['Chr1','Chr1','Chr2','Chr2','Chr2'],
                     'spos':[1,5,2,9,25],'epos':[3,14,7,20,35],'lev':[0.5,0.6,0.7,0.8,0.9]})
#
df_merge_temp = pd.merge(df_a, df_b,on=['chrom','spos','epos'], how='inner',suffixes=('_a', '_b'))
df_merge_temp

chrom  epos  lev_a  spos  lev_b
0  Chr1     3    0.1     1    0.5
1  Chr1    14    0.2     5    0.6
2  Chr2     7    0.3     2    0.7
3  Chr2    20    0.4     9    0.8

In [4]:
df_merge_temp = df_merge_temp[['chrom','spos','epos','lev_a','lev_b']]
df_merge_temp

chrom  spos  epos  lev_a  lev_b
0  Chr1     1     3    0.1    0.5
1  Chr1     5    14    0.2    0.6
2  Chr2     2     7    0.3    0.7
3  Chr2     9    20    0.4    0.8

### df列名修改

> 列名修改可以分成两种情况，1. 原df没有列名，或想把所有列名都修改了(只修改某些也可以) 2. 只修改某列的列名

- 情况1：

In [6]:
df_merge_temp.columns = ['chrom','spos','epos','lev_A','lev_C']
df_merge_temp

chrom  spos  epos  lev_A  lev_C
0  Chr1     1     3    0.1    0.5
1  Chr1     5    14    0.2    0.6
2  Chr2     2     7    0.3    0.7
3  Chr2     9    20    0.4    0.8

- 情况2：

In [7]:
df_merge_temp.rename(columns={ df_merge_temp.columns[4]: 'lev_B' }, inplace=True)
df_merge_temp

chrom  spos  epos  lev_A  lev_B
0  Chr1     1     3    0.1    0.5
1  Chr1     5    14    0.2    0.6
2  Chr2     2     7    0.3    0.7
3  Chr2     9    20    0.4    0.8

### 包含或不包含某个字段

In [ ]:
# 第一列字段包含'Chr1'的行
df_merge_temp.loc[df_merge_temp.chrom.str.contains('Chr1')]
#第一列字段不包含'Chr1'的行
df_merge_temp.loc[df_merge_temp.chrom.str.contains('Chr1')==False]

# DataFrame数值计算问题

In [ ]:
df.apply(lambda s:s*2+1)

In [65]:
df.apply(pd.Series.value_counts)

A    B    C
1  1.0  NaN  NaN
2  1.0  NaN  NaN
3  1.0  NaN  NaN
4  NaN  1.0  NaN
5  NaN  1.0  NaN
6  NaN  1.0  NaN
7  NaN  NaN  1.0
8  NaN  NaN  1.0
9  NaN  NaN  1.0

In [ ]:
### 对某一列的操作可以使用map函数
df.A.map(lambda s:s*2+1)

通过某列值的大小新增一列,下面是一个实战中的例子:

`merge_fpkm_DEG['DEG_statue'] = merge_fpkm_DEG.apply(lambda x: 'Down' if x.log2FoldChange>=0 else 'Up', axis=1)`

# Python中创建数组

## 使用np.array()从Python列表创建数组

In [63]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [66]:
# numpy中要求数组中的数据类型必须是一样的，如果类型不匹配，会尝试向上转换
np.array([3.14,2,7])

array([3.14, 2.  , 7.  ])

In [65]:
#数据向上转换为字符串类型
np.array([3.14,2,'Hello'])

array(['3.14', '2', 'Hello'], dtype='<U32')

In [67]:
# 嵌套列表，构成多维数组
np.array([[1,2,3],
          [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.array([range(i,i+2) for i in [1,4,7]])

array([[1, 2],
       [4, 5],
       [7, 8]])

## 从头创建数组

常用方法：
- np.zeros()
- np.ones()
- np.full()
- np.arange()
- np.linespace()
- np.eys()
- np.random.random()
- np.random.normal()
- np.random.randint()

In [69]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [71]:
np.zeros([3,4],dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [73]:
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [74]:
#创建一个4x4元素全部为5.6的矩阵
np.full([4,4],5.6)

array([[5.6, 5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6, 5.6]])

In [85]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
np.arange(1,12,2).reshape([2,3])

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [86]:
#0到1均分为5个数
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [104]:
#创建3x3的矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
#0-1均匀分布的随机数
np.random.random((1,10))

array([[0.32552948, 0.21972306, 0.11947702, 0.77925181, 0.17206905,
        0.34286331, 0.79815805, 0.38474013, 0.38580208, 0.92594406]])

In [102]:
#均值为1，方差为2的正态分布数组
np.random.normal(1,2,(3,3))

array([[ 2.73507356,  1.36209193, -1.83913605],
       [ 2.06732319,  0.03486259, -0.12460225],
       [-1.23873567,  0.12988291, -1.72001713]])

In [103]:
#0-9内随机整数
np.random.randint(0,9,(4,4))

array([[7, 5, 3, 8],
       [7, 6, 3, 5],
       [7, 2, 2, 7],
       [4, 3, 0, 5]])

# Numpy数组属性

In [119]:
# 设置种子，确保每次执行可以产生相同的随机数组
np.random.seed(2)

In [120]:
#一维数组
x1 = np.random.randint(10,size=6)
x1

array([8, 8, 6, 2, 8, 7])

In [121]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[2, 1, 5, 4],
       [4, 5, 7, 3],
       [6, 4, 3, 7]])

In [122]:
x3 = np.random.randint(10,size=(2,3,4))
x3

array([[[6, 1, 3, 5],
        [8, 4, 6, 3],
        [9, 2, 0, 4]],

       [[2, 4, 1, 7],
        [8, 2, 9, 8],
        [7, 1, 6, 8]]])

数组的属性：
- ndim, 数组的维度
- shape, 数组每个维度大小(个人喜欢用数组的形状来描述这个属性)
- size, 数组的总大小
- dtype, 数组数据类型

In [115]:
print('x3维度:{}\nx3形状:{}\nx3总大小:{}\n数组数据类型:{}'.format(x3.ndim,x3.shape,x3.size,x3.dtype))

x3维度:3
x3形状:(2, 3, 4)
x3总大小:24
数组数据类型:int32


# Numpy数组索引，切片，重塑

## 基本索引

In [123]:
x1

array([8, 8, 6, 2, 8, 7])

In [124]:
x1[0]

8

In [125]:
x1[-1]

7

In [126]:
x1[1:4]

array([8, 6, 2])

In [127]:
x2

array([[2, 1, 5, 4],
       [4, 5, 7, 3],
       [6, 4, 3, 7]])

In [128]:
x2[1,1]

5

In [129]:
x2[1,-1]

3

In [130]:
#获取第三列
x2[:,2]

array([5, 7, 3])

In [146]:
#获取第二行
x2[1,:] #取行时，可以省略空切片，即等价，x2[1]

array([4, 5, 7, 3])

In [133]:
#利用索引修改元素值
x1[0] = 5
x1

array([5, 8, 6, 2, 8, 7])

In [135]:
#注意：当把浮点数插入到整型数组时，其将会被截短
x1[1] = 2.5
x1

array([5, 2, 6, 2, 8, 7])

In [136]:
#隔取
x1[::2]

array([5, 6, 8])

In [137]:
#逆序
x1[::-1]

array([7, 8, 2, 6, 2, 5])

In [142]:
#所有行，每隔一列
x2[:,::2]

array([[2, 5],
       [4, 7],
       [6, 3]])

## 花哨的索引

In [311]:
x3 = np.arange(5,16)
x3

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [312]:
# 索引值为1，3，5的元素的值
x3[[1,3,5]]

array([ 6,  8, 10])

In [328]:
# 利用花哨的索引修改值
x3[[1,3,5]] = 0 
x3

array([ 5,  0,  7,  0,  9,  0, 11, 12, 13, 14, 15])

In [313]:
ind = np.array([[1,5],
               [7,9]])
ind

array([[1, 5],
       [7, 9]])

In [314]:
x3[ind]

array([[ 6, 10],
       [12, 14]])

> 注意：利用花哨的索引，结果的形状与索引的形状一致，而不是与被索引数组形状一直

In [317]:
x4 = np.arange(12,24).reshape(3,4)
x4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [320]:
x4[[0,2],[1,3]]

array([13, 23])

In [322]:
row = np.array([0,1,2])
col = np.array([2,1,3])

In [324]:
row[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [325]:
mask = np.array([1,0,1,0],dtype=bool)

In [327]:
#花哨索引与掩码组合(掩码下文有提到)
x4[row[:,np.newaxis],mask]

array([[12, 14],
       [16, 18],
       [20, 22]])

## 关于数组切片非常重要的说明

> 切片返回数组数据**视图**,而非数值数据**副本**,这也是numpy数组与python列表不同的地方

举例解释一下**视图**

In [149]:
print(x2)

[[2 1 5 4]
 [4 5 7 3]
 [6 4 3 7]]


In [151]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[2 1]
 [4 5]]


In [152]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  1]
 [ 4  5]]


In [153]:
print(x2)

[[99  1  5  4]
 [ 4  5  7  3]
 [ 6  4  3  7]]


> **视图**的意思就是，当我们切片一个numpy子数组时，当改变了子数组的元素后，原始数组也会跟着改变

> 在处理大数据集的时候这将会带来很大优势

> 创建数组副本：

In [155]:
#数组副本就是数组的一份copy
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[99,  1],
       [ 4,  5]])

In [156]:
x2_sub_copy[0,0] = 55
x2_sub_copy

array([[55,  1],
       [ 4,  5]])

In [157]:
# 修改副本子组，原始数组并不会发生改变
x2

array([[99,  1,  5,  4],
       [ 4,  5,  7,  3],
       [ 6,  4,  3,  7]])

## 数组重塑

In [161]:
# 通过reshape方法改变数组的形状
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [162]:
# 通过np.newaxis获得行向量，将一维数组转换为二维数组
x = np.arange(8)
x[np.newaxis,:]

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [163]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

# 数组拼接与分裂

连接两个或多个数组一般用到：
- np.caoncatenate
- np.vstack
- np.hstack
- np.dstack

In [171]:
# np.concatenate拼接一维数组
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [172]:
z = np.array([9,10,11,12])
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [169]:
# np.concatenate拼接二维数组
grid1 = np.arange(8).reshape(2,4)
grid2 = np.arange(8,16).reshape(2,4)
np.concatenate([grid1,grid2])  # 默认axis=0,沿着列轴拼接

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [170]:
np.concatenate([grid1,grid2],axis=1) # set axis=1 沿着横轴拼接

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [173]:
# 对于横向与纵向拼接有专门的方法
np.vstack([x,grid1])

array([[1, 2, 3, 4],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [174]:
np.vstack([grid1,grid2])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [175]:
np.hstack([grid1,grid2])

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [176]:
# np.dstack将沿着第三个维度进行拼接,这个不是很好理解
np.random.seed(3)
d1 = np.random.randint(0,9,size=[3,4])
np.random.seed(4)
d2 = np.random.randint(0,9,size=[3,4])
d1

array([[8, 3, 8, 8],
       [0, 5, 3, 5],
       [7, 6, 0, 4]])

In [178]:
d2

array([[7, 5, 1, 8],
       [7, 8, 2, 7],
       [7, 7, 8, 4]])

In [182]:
np.dstack([d1,d2])

array([[[8, 7],
        [3, 5],
        [8, 1],
        [8, 8]],

       [[0, 7],
        [5, 8],
        [3, 2],
        [5, 7]],

       [[7, 7],
        [6, 7],
        [0, 8],
        [4, 4]]])

数组的分裂一般用到:
- np.split
- np.hsplit
- np.vsplit

In [185]:
# np.split接受第一个参数为数组，第二个参数为分裂位点信息
long_array = np.arange(12)
long_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [186]:
np.split(long_array,[3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11])]

In [187]:
grid3 = np.arange(16).reshape(4,4)
grid3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [188]:
np.vsplit(grid3,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [189]:
np.hsplit(grid3,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# 数组计算

## 通用函数
numpy中通过一些通用函数进行向量化操作运行速度上会得到很大提高，而且计算十分方便

### 标量与数组之间的基本运算

In [193]:
x * 2

array([2, 4, 6, 8])

In [194]:
1 / x

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [195]:
x ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [196]:
x - 1

array([0, 1, 2, 3])

In [197]:
x + 2

array([3, 4, 5, 6])

In [198]:
x % 2

array([1, 0, 1, 0], dtype=int32)

In [200]:
# 组合运算
-(x*2 + 1) ** 2

array([ -9, -25, -49, -81], dtype=int32)

Numpy中常见运算实现：
- 加 np.add
- 减 np.subtract
- 取负 np.negative
- 乘法 np.multiply
- 除法 np.divide
- 地板除法 np.floor_divide
- 指数运算 np.power np.exp np.exp2
- 对数运算 np.log np.log2 np.log10
- 取余数 np.mod
- 取绝对值 np.absolute 或使用别名np.abs

>一些示例

In [202]:
x

array([1, 2, 3, 4])

In [203]:
#取负
y = -x
y

array([-1, -2, -3, -4])

In [204]:
# e^x
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [205]:
# 2^x
np.exp2(x)

array([ 2.,  4.,  8., 16.])

In [206]:
#3^x
np.power(3,x)

array([ 3,  9, 27, 81], dtype=int32)

In [207]:
#ln(x)
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [208]:
#log2(x)
np.log2(x)

array([0.       , 1.       , 1.5849625, 2.       ])

In [209]:
#log10(x)
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

### 一些说明

> 既然有了基本运算符，为什么numpy还要有自己的一套运算方法呢，一个方面就是numpy的运算方法还包含许多特殊的接口方便使用，另为这些方法还存在自己的一些属性与方法，大大扩展了计算的功能，下面可以看到

In [212]:
x + 2

array([3, 4, 5, 6])

In [213]:
np.add(x,2)

array([3, 4, 5, 6])

In [215]:
y = np.zeros(4)
np.add(x,2,out=y)
y

array([3., 4., 5., 6.])

In [217]:
y = np.zeros(8)
np.power(2,x,out=y[::2])
y

array([ 2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

### 聚合

In [220]:
x

array([1, 2, 3, 4])

In [218]:
#通过np.add的reduce方法实现数组求和
np.add.reduce(x)

10

In [219]:
np.multiply.reduce(x)

24

### 外积
类似于九九乘法表，两两元素相乘

In [222]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

## Numpy中的聚合函数

### 求和

#### 一维数组聚合

In [224]:
L = np.arange(10)
np.sum(L)

45

In [227]:
# 更简洁的语法形式: 通过数组对象直接调用sum方法
L.sum()

45

In [228]:
#比较数组三种求和方法：
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)
%timeit big_array.sum()

106 ms ± 2.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
964 µs ± 21.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
812 µs ± 113 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


> 结论：后两种时间差不多，要比第一中方式快了很多

In [231]:
# 最大值与最小值
np.max(x)

4

In [232]:
np.min(x)

1

In [233]:
# 简洁的形式
print(x.min(),
x.max())

1 4


#### 多维度的聚合

> 多维度聚合默认返回所有元素的聚合结果，可以通过指定参数axis=0 计算每列聚合值，axix=1 计算每行聚合值

> axis关键字指定的时数组将会被折叠的维度，所以axis=0,意味着行将会被折叠，也就是计算每列的聚合值

In [234]:
grid1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [235]:
grid1.sum()

28

In [236]:
# 列聚合值计算
grid1.sum(axis=0)

array([ 4,  6,  8, 10])

In [238]:
# 行聚合值计算
grid1.sum(axis=1)

array([ 6, 22])

In [243]:
np.(grid1)

0

numpy中可用的聚合函数清单：
- np.sum 和
- np.prod 积
- np.mean 均值
- np.std 标准差
- np.var 方差
- np.min 最小值
- np.max 最大值
- np.argmin 最小值索引
- np.argmax 最大值索引
- np.median 中位数
- np.percentile 计算基于元素排序的统计值
- np.any 验证任何一个元素是否为真
- np.all 验证所有元素是否为真

> 说明几个聚合函数

In [251]:
x2 = np.arange(18)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [256]:
# np.percentile( )用于计算位于前百分之多少需要达到的数值
# 比如，一个班级学生语文的成绩，想知道领先80%学生语文成绩，需要达到多少分，这时候就可以通过这个函数去计算
np.percentile(x2,80)

13.600000000000001

> np.any(),接受一个可迭代对象，有一个元素为True则返回True,如果可迭代对象为空，则返回False

> np.all(),接受一个可迭代对象，所有元素为True则返回True,如果可迭代对象为空，则返回True

In [259]:
np.any([0,1,2,3])

True

In [260]:
np.all([0,1,2,3])

False

In [261]:
np.any([])

False

In [262]:
np.all([])

True

In [264]:
# 可以利用这个函数判断两个数组是否相等
np.all(np.array([1,2,3] == np.array([1,2,3])))

True

In [265]:
np.all(np.array([1,2,3] == np.array([1,2,5])))

False

In [268]:
# 数组是否相等也可以通过np.array_equal()来判断
np.array_equal(np.array([1,2,3]),np.array([1,2,3]))

True

# broadcasting (广播)

> numpy中广播的概念就像是多米诺骨牌一样

前面的数组基本计算中已经有涉及广播的概念了，只是没有提及，下面通过示例能够更直接的感受广播的强大之处

## 广播介绍

In [273]:
a = np.array([1,2,5])
b = np.array([3,6,9])
a + b

array([ 4,  8, 14])

In [275]:
a + 5 #相当于 a + np.array([5,5,5]),自动的将5进行了扩展

array([ 6,  7, 10])

In [276]:
M = np.ones([3,3])
M + a

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

In [283]:
c = np.arange(3)[np.newaxis,:]
d = np.arange(3)[:,np.newaxis]
c + d

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# 比较，掩码与布尔逻辑

> 布尔掩码数组就像是一个筛子，筛孔为True，符合条件(为真)的元素将从筛孔中被挑选出来

## 关于布尔数组

In [286]:
#包含bool数据类型的数组就是布尔数组，比如下面的：
np.array([False,True,True,False,True],dtype=bool)

array([False,  True,  True, False,  True])

> 可以通过类似通用函数的比较操作来获取布尔数组

In [288]:
x < 3

array([ True,  True, False, False])

In [289]:
x > 3

array([False, False, False,  True])

In [290]:
x <= 3

array([ True,  True,  True, False])

In [291]:
x >= 3

array([False, False,  True,  True])

In [292]:
x != 3

array([ True,  True, False,  True])

In [293]:
x == 3

array([False, False,  True, False])

In [294]:
# 复合表达式实现对两个数组的逐元素比较
(x * 2) == (x ** 2)

array([False,  True, False, False])

numpy中比较操作符对应的通用函数:

    == np.equal
    != np.not_equal
    < np.less
    <= np.less_equal
    > np.greater
    >= np.greater_equal

## 操作布尔数组

### 统计个数

In [295]:
# x中元素小于3的数目
np.count_nonzero(x < 3)

2

In [296]:
# 也可以通过np.sum()实现上面的目的，因为False会被解释为0，True会被解释为1
# 而且通过np.sum() 的axis我们还能知道每行或列有多少符合条件的数目
np.sum(x < 3)

2

In [297]:
# 是否存在大于3的元素
np.any(x > 3)

True

In [298]:
# 是否存在小于0的元素
np.any(x < 0)

False

In [299]:
# 是否所有元素都小于4
np.all(x < 4)

False

> 另外np.any()和np.all()也可以用于沿着特定的坐标轴

### 布尔运算符

> 通过Python中逐位运算符&，|，^，~ 来实现

In [301]:
# x中大于1并且小于4的元素个数
np.sum((x > 1) & (x < 4))

2

> 注意：因为运算优先级的规则，上面每个条件外的括号是必须的，不然会导致运行出错

In [303]:
#上面的运算等价于
np.sum(~((x <= 1) | (x >= 4)))

2

布尔运算符对应的通用函数：

    & np.bitwise_and
    | np.bitwise_or
    ^ np.bitwise_xor
    ~ np.bitwise_not

## 将布尔数组作为掩码

In [307]:
np.random.seed(5)
x = np.random.randint(0,9,size=[3,4])
x

array([[3, 6, 6, 0],
       [8, 4, 7, 0],
       [0, 7, 1, 5]])

In [308]:
# 下面展示掩码操作
x[x < 5]

array([3, 0, 4, 0, 0, 1])